### ISSUE TITLE
UVA Engineering is also offering application fee waivers

### ISSUE THREAD

**Issue by mshoaib6** [KaiserWhoLearns/CS-PhD-Application-fee-waivers#7]
https://engineering.virginia.edu/departments/biomedical-engineering/apply/application-fee-waivers#:~:text=The%20School%20of%20Engineering%20and,to%20all%20our%20graduate%20programs.

Applicants are not required to submit a form or enter a code to receive the fee waiver as it will be automatically applied to the application.

**Comment by KaiserWhoLearns** [comment]
Thank you. This is addressed in [this commit](https://github.com/KaiserWhoLearns/CS-PhD-Application-fee-waivers/commit/347d8b97987054e54b404c6d55f63e362cb38ec3).
